<%@ Page Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="CollegeView.aspx.cs" Inherits="OnlineCollgeAdmissionWeb.CollegeView" %>
<asp:Content ID="ContentCollegeViewHeder" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="ContentCollegeView" ContentPlaceHolderID="cphMainHolder" runat="server">
     <div align ="Center">      
        <asp:GridView ID="gvCollegeTable" runat="server" AutoGenerateColumns="False" DataKeyNames="CollegeCode"
            OnRowUpdating="GvCollegeTable_RowUpdating" OnRowCancelingEdit="GvCollegeTable_RowCancelingEdit" ShowFooter="True" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" OnRowEditing="GvCollegeTable_RowEditing" OnRowDeleting="GvCollegeTable_RowDeleting" 
            BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" ForeColor="Black">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:TemplateField HeaderText="S.No">
                    <ItemTemplate>
                        <asp:Label ID="lblSerialNumber" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                       <asp:LinkButton ID ="btnInsert" Text ="Insert" runat ="server" OnClick ="LbInsert_Click" /> 
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="College Code">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("CollegeCode")%>' runat="server"/>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtCollegeCodeFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="College Name">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("CollegeName")%>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtCollegeNameFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Website">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("CollegeWebsite")%>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtCollegeWebsiteFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Fees">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("admissionFee")%>' runat="server" />
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtAdmissionFee" Text='<%# Eval("AdmissionFee")%>' runat="server" />
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtAdmissionFeeFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Seats">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("TotalSeats ")%>' runat="server" />
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtSeats" Text='<%# Eval("TotalSeats")%>' runat="server" />
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtSeatsFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:HyperLinkField />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" ForeColor="White" Font-Bold="True" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
    </div>
</asp:Content>
