<%@ Page Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="CollegeView.aspx.cs" Inherits="OnlineCollgeAdmissionWeb.CollegeTable" %>

<asp:Content ID="ContentCollegeHeader" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="ContentCollege" ContentPlaceHolderID="cphMainHolder" runat="server">
    <div>
        <asp:GridView ID="gvCollegeTable" runat="server" AutoGenerateColumns="False" DataKeyNames="CollegeCode"
            OnRowUpdating="GvCollegeTable_RowUpdating" OnRowCancelingEdit="GvCollegeTable_RowCancelingEdit" ShowFooter="True" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" OnRowEditing="GvCollegeTable_RowEditing" OnRowDeleting="GvCollegeTable_RowDeleting">
            <Columns>
                <asp:TemplateField HeaderText="S.No">
                    <ItemTemplate>



                        <asp:Label ID="lblSerialNumber" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:LinkButton ID ="btnInsert" Text ="Insert" runat ="server" OnClick ="LbInsert_Click" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="College Code">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("CollegeCode")%>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtCollegeCodeFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="College Name">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("CollegeName")%>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtCollegeNameFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Website">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("CollegeWebsite")%>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtCollegeWebsiteFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Fees">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("admissionFee")%>' runat="server" />
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtAdmissionFee" Text='<%# Eval("AdmissionFee")%>' runat="server" />
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtAdmissionFeeFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Seats">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("TotalSeats ")%>' runat="server" />
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtSeats" Text='<%# Eval("TotalSeats")%>' runat="server" />
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtSeatsFooter" runat="server" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:HyperLinkField />
            </Columns>
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#FAFAE7" />
            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
            <SortedDescendingCellStyle BackColor="#E1DB9C" />
            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
    </div>
</asp:Content>
